# Generated by Django 5.2.3 on 2025-06-20 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('KOREAN', '한식'), ('JAPANESE', '일식'), ('CHINESE', '중식'), ('WESTERN', '양식'), ('ETC', '기타')], default='기타', max_length=10)),
                ('food', models.CharField(max_length=20)),
            ],
        ),
    ]
