# Generated by Django 5.2.3 on 2025-06-20 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='category',
            field=models.CharField(choices=[('KOREAN', '한식'), ('JAPANESE', '일식'), ('CHINESE', '중식'), ('WESTERN', '양식'), ('ETC', '기타')], default='ETC', max_length=10),
        ),
        migrations.AlterField(
            model_name='menu',
            name='food',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
